<a href="https://colab.research.google.com/github/Udaykiran06-art/MACHINE-LEARNING-TRAIN-TEST-DATASETS/blob/main/ML_TRAIN_AND_TEST_DATASETS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Creating an array
import numpy as np
dataset = np.arange(10)
print(dataset)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Creating an array and splitting dataset
import numpy as np
from sklearn.model_selection import train_test_split
dataset = np.arange(10)
result = train_test_split(dataset)
print(dataset)
print(result)

[0 1 2 3 4 5 6 7 8 9]
[array([8, 0, 4, 9, 2, 6, 7]), array([1, 5, 3])]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

X_train, X_test = train_test_split(dataset)

print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[0 9 2 8 6 1 7]
[3 5 4]


In [ ]:
#Creating an array and spiltting
import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

X_train,X_test = train_test_split(dataset,test_size=4)

print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[7 3 1 5 9 4]
[6 2 0 8]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

x_train,X_test = train_test_split(dataset,train_size = 6)

print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[7 3 1 5 9 4]
[1 0 9 3]


In [ ]:
#Creating an array and splitting

import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

X_train,X_test = train_test_split(dataset,train_size=0.4)

print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[5 2 4 9]
[3 0 8 1 7 6]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

X_train,X_test = train_test_split(dataset,test_size = 0.6)

print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[9 0 4 5]
[7 8 3 2 6 1]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

X_train,X_test = train_test_split(dataset,train_size=4,test_size=4)
print(dataset)
print()
print(X_train)
print(X_test)

[0 1 2 3 4 5 6 7 8 9]

[7 8 6 9]
[3 0 1 5]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split

dataset = np.arange(10)

X_train,X_test = train_test_split(dataset,train_size=4,test_size=10)

print(dataset)
print()
print(X_train)
print(X_test)

ValueError: test_size=10 should be either positive and smaller than the number of samples 10 or a float in the (0, 1) range

In [ ]:
#Creating an array and splitting
import numpy as np
dataset = np.arange(20)
print(dataset)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split
dataset = np.arange(20).reshape(2,10)

print(dataset)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [ ]:
#Creating an array and splitting
import numpy as np
dataset = np.arange(20).reshape(2,10).T
print(dataset)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]


In [ ]:
#Creating an array and splitting
import numpy as np
X = np.arange(20).reshape(2,10).T
y = np.arange(10)

print(X)
print()
print(y)

[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]
 [ 6 16]
 [ 7 17]
 [ 8 18]
 [ 9 19]]

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Creating an array and splitting
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(20).reshape(2,10).T
y = np.arange(10)

X_train,X_test,y_train,y_test = train_test_split(X,y)

print(X_train)
print()
print(X_test)
print()
print(y_train)
print()
print(y_test)

[[ 1 11]
 [ 9 19]
 [ 5 15]
 [ 4 14]
 [ 0 10]
 [ 3 13]
 [ 2 12]]

[[ 7 17]
 [ 8 18]
 [ 6 16]]

[1 9 5 4 0 3 2]

[7 8 6]


In [ ]:
#Creating an array and spiltting
import numpy as np
from sklearn.model_selection import train_test_split
X = np.arange(20).reshape(2,10).T
y = np.arange(10)

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)

print(X_train)
print()
print(X_test)
print()
print(y_train)
print()
print(y_test)

[[ 9 19]
 [ 1 11]
 [ 6 16]
 [ 7 17]
 [ 3 13]
 [ 0 10]
 [ 5 15]]

[[ 2 12]
 [ 8 18]
 [ 4 14]]

[9 1 6 7 3 0 5]

[2 8 4]
